/* auto-generated by gen_strings.py */
#ifndef STRINGS_H
#define STRINGS_H

#include <stdint.h>

#define STR_C9E8_D6C3  ((const uint8_t*)"\xC9\xE8\xD6\xC3")  // 设置
#define STR_C4E3_BAC3_CAC0_BDE7  ((const uint8_t*)"\xC4\xE3\xBA\xC3\xCA\xC0\xBD\xE7")  // 你好世界
#define STR_CEC2_B6C8  ((const uint8_t*)"\xCE\xC2\xB6\xC8")  // 温度
#define STR_C8B7_B6A8  ((const uint8_t*)"\xC8\xB7\xB6\xA8")  // 确定
#define STR_B7B5_BBD8  ((const uint8_t*)"\xB7\xB5\xBB\xD8")  // 返回

#endif
