# -*- coding: utf-8 -*-
"""
gen_strings.py - Chinese text to GB2312 hex header generator
"""
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
INPUT_FILE  = os.path.join(SCRIPT_DIR, "scripts.txt")
OUTPUT_FILE = os.path.join(SCRIPT_DIR, "..", "keil", "Core", "Inc", "strings.h")

def cn_to_gb2312(text):
    try:
        return text.encode("gb2312")
    except UnicodeEncodeError as e:
        print(f"  [!] encode failed: {e}")
        return None

def make_macro_name(text):
    name = ""
    for ch in text[:4]:
        if '\u4e00' <= ch <= '\u9fff':
            gb = ch.encode("gb2312")
            name += f"_{gb[0]:02X}{gb[1]:02X}"
        else:
            name += f"_{ord(ch):02X}"
    return f"STR{name}"

def main():
    if not os.path.exists(INPUT_FILE):
        with open(INPUT_FILE, "w", encoding="utf-8") as f:
            f.write("# one phrase per line\n")
            f.write("hello\n")
            f.write("world\n")
        print(f"template created: {INPUT_FILE}")
        return

    lines = []
    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            lines.append(line)

    if not lines:
        print("empty")
        return

    macros = []
    for text in lines:
        gb = cn_to_gb2312(text)
        if gb is None:
            continue
        # produce \xC9\xE8 style escapes
        parts = ["\\x%02X" % b for b in gb]
        hex_str = "".join(parts)
        name = make_macro_name(text)
        macros.append((name, hex_str, text))

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("/* auto-generated by gen_strings.py */\n")
        f.write("#ifndef STRINGS_H\n#define STRINGS_H\n\n")
        f.write("#include <stdint.h>\n\n")
        for name, hex_str, comment in macros:
            f.write('#define %s  ((const uint8_t*)"%s")  // %s\n' % (name, hex_str, comment))
        f.write("\n#endif\n")

    print("generated: %s" % OUTPUT_FILE)
    for name, _, comment in macros:
        print("  %s  <- %s" % (name, comment))

if __name__ == "__main__":
    main()
